---
- name: Our first playbook
  hosts: raiders
  gather_facts: yes  # this is a default but we set it as a reminder to talk about
                    # this is also called setup module or setup.py
                    #
  tasks:
          - name: Install an application with apt
            apt: 
              state: "{{ lenny }}"
              name: [sl, bastet, ninvaders] 
              #  - sl
              #  - bastet
              #  - ninvaders
            become: yes

