---
- name: a play with python and jinja
  hosts: localhost

  vars:
          test_list:
                  - 192.168.2.1
                  - 10.10.0.2
                  - host.example.org
                  - 192.168.70.0/24
                  - 'fe80::100/10'
                  - True
                  - 'witcher 3: The Wild Hunt'
                  - 'Earl Grey Tea, hot'
                    mytest_string: "NCC1701 USS Enterpris"
                    my addresses: ['192.168.2.101', '10.0.3.50', '172.171.32.1']

  tasks:
                  - name: I just want some IPs
                    debug:
                            msg: "{{ test_list | ipaddr }}"

                  - name: make me a big mac
                    debug:
                            msg: "{{ '52:54:00' | random_mac }}"

                  - name: test if it ends in 'prise'
                    debug:
                            msg: "{{ mytest_string.endswitch('prise') }}"

                  - name: run only if test is true
                    debug: 
                            msg: Ahh the enterprise! but is it subclass A, B, C, or D?
                    when: mytest_string.endswitch('prise')

                  - name: pop the number 50 on the screen
                    debug:
                            msg: "{{ (myaddresses|ipaddr('10.0.0.0/8'))[0].split(.)[3] }}"
