---
- name: learning some jinja tricks
  hosts: localhost
  gather_facts: yes

  vars:
          jarlist: [1,1,1,1,1,5]
          repeatlist: [1,2,2,2,4,4,4,4,9,9,9,9,9]
          repeat2list: [5,5,5,5,5,5,6,7]
          complexlist: [6,7,8(9,10,22),87]

  tasks:
          - name: min filter
            debug:
                    msg: "show me the lowest value: '{{ jarlist|min }}"

          - name: max filter
            debug:
                    msg: "show me the highest value: '{{ jarlist|max }}'"

          - name: flatten lists (good for looping)
            debug:
                    msg: "Show me a loop with flatten {{ item }}"
            loop: "{{ complexlist|flatten }}"

          - name: drop items that repeat, we want a unique set
            debug:
                    msg: "we just want the unique set {{ repeatlist|unique }}"

          - name: union of two lists
            debug:
                    msg: "we want a UNION (wha the heck is union) of two list {{ repeatlist|union|(repeat2list) }}"

          - name: get the digg between two lists
            debug:
                    msg: "diff of two lists: {{ repeatlist |(repeat2list) }}"


