---
- name: gather fact on eos switch
  eos_facts:
          gather_subset: all
  become: yes

- name: create a directory for backing up configs
  file:
          path: ~/ans/backup/
          state: directory

- name: what the heck is in ansible_facts
  debug:
          var: ansible_facts

- name: Use copy to evac info from playbook to controller
  copy:
          dest: "~/ans/backup/{{ inventory_hostname }}.bkup"
          content: "{{ ansible_facts.net_config }}"

- name: Archive backup config file
  archive:
    path:  "~/ans/backup/{{ inventory_hostname }}.bkup"
    dest: "~/ans/backup/{{ inventory_hostname }}-{{ ansible_date_time.iso8601_basic }}.tar"
    remove: yes

